vscode:
    extensions:
        - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
        - CoenraadS.bracket-pair-colorizer@1.0.61:+jQByqALW0iXkhpd2yzYzQ==
        - streetsidesoftware.code-spell-checker@1.10.2:IKNWSiKNhoiWZ0g+IVw/mA==
        - naumovs.color-highlight@2.3.0:6nKORbxgnWjNaN6xACiaQQ==
        - entepe85.gitlens@11.0.2:FJr9g9ULgySyb06Us88Qww==
        - ms-vscode.hexeditor@1.3.0:8TVKV0NawzXxZakIZ4cQFA==
        - esbenp.prettier-vscode@5.8.0:cd2Jz796EPVnD5zeCyctPw==
        - Tyriar.sort-lines@1.9.0:39TPtnzbLWepVuVCVtlO3g==
        - ExodiusStudios.comment-anchors@1.9.1:Bq4ern4hXIzy2ib+mIWwiw==

image:
    file: .gitpod.Dockerfile

tasks:
    - init: npm install
      prebuild: tsc

github:
    prebuilds:
        master: true
        branches: true
        pullRequests: true
        pullRequestsFromForks: true
        addCheck: true
        addComment: true
